# Generated by Django 4.1.7 on 2023-03-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_products_delete_loginform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Productss',
        ),
    ]
